/**
 * Source byte hygiene.
 *
 * Every source file in this package must be valid UTF-8 and must not contain control bytes
 * other than tab (0x09) and newline (0x0A).
 *
 * WHY THIS EXISTS
 * ---------------
 * A raw NUL byte was once written into a template literal in src/executor.ts. Somebody meant
 * to write the two-character escape and typed the byte instead. Nothing complained:
 *
 *   - `tsc` was clean and the file compiled.
 *   - Every vitest test passed.
 *   - `file src/executor.ts` started reporting `data` instead of text.
 *   - GNU grep silently treated the file as binary: exit code 1, no output, no
 *     "binary file matches" warning, no diagnostic of any kind.
 *
 * The last one is the expensive part. Several greps against that file came back empty, which
 * read as "this feature was never wired up" when in fact it was fully wired. There was no error
 * message anywhere in the loop, so there was nothing to diagnose - just silence. That cost an
 * afternoon and nearly produced a false bug report.
 *
 * The fix is not to ban the idea (a NUL separator in a cache key is a perfectly good idea,
 * because it cannot appear in either component) - it is to ban the raw byte. Write the escape.
 *
 * WHAT COUNTS AS A CONTROL BYTE HERE
 * ----------------------------------
 * Every byte below 0x20 except tab and newline, plus 0x7F (DEL). Carriage return (0x0D) is
 * therefore rejected too: this package is LF-only today, and a stray lone CR is exactly the
 * kind of invisible byte this check exists to surface. DEL is included because it is equally
 * invisible in an editor and equally likely to be an accident.
 *
 * Bytes 0x80 and above are only checked for UTF-8 well-formedness. The C1 control characters
 * (U+0080-U+009F) are deliberately not rejected: they are valid UTF-8, they do not make grep
 * give up, and rejecting them would flag legitimate text.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Package root. Resolves correctly both from src/ (vitest, vite-node, bun) and from dist/
 * (compiled output), because both live exactly one directory below the package root.
 */
export const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** The only control bytes permitted anywhere, in any file, with no exceptions. */
export const ALLOWED_CONTROL_BYTES: ReadonlySet<number> = new Set([0x09, 0x0a])

/**
 * Directories skipped wherever they appear in the scanned tree, each with the reason it is
 * skipped. Skipping is deliberate and enumerated: there is no ".gitignore-like" pattern
 * matching, so nothing gets excluded by accident.
 */
export const SKIPPED_DIRECTORIES: Readonly<Record<string, string>> = {
  node_modules: 'third-party code - not ours to police, and full of genuinely binary files',
  dist: 'build output - regenerated from src, so a bad byte is caught at its source instead',
  'dist-packaged': 'extension build output - same reasoning as dist',
  'dist-release': 'release build output - same reasoning as dist',
  tmp: 'scratch output from test runs (screenshots, traces, videos) - not source',
  coverage: 'generated coverage reports',
  '.git': 'the git object database is binary by design',
  '.wrangler': 'generated deploy artifacts',
  '.vercel': 'generated deploy artifacts',
}

/**
 * File extensions skipped, each with the reason. Everything not listed here IS scanned, which
 * is the important direction: a newly introduced source extension (.tsx, .cts, .mts, .svelte,
 * whatever) is covered automatically rather than silently escaping the check.
 *
 * The cost of that choice is that adding a new kind of binary fixture makes this check fail
 * until the extension is added below. That is intentional - the failure message says so - and
 * it is a far better failure than a source extension quietly going unchecked.
 */
export const SKIPPED_EXTENSIONS: Readonly<Record<string, string>> = {
  '.png': 'binary image - test/video-golden/*.png golden frames and src/assets/*.png fixtures',
  '.jpg': 'binary image',
  '.jpeg': 'binary image',
  '.gif': 'binary image',
  '.webp': 'binary image',
  '.avif': 'binary image',
  '.ico': 'binary image',
  '.mp4': 'binary video',
  '.webm': 'binary video',
  '.mov': 'binary video',
  '.woff': 'binary font',
  '.woff2': 'binary font',
  '.ttf': 'binary font',
  '.otf': 'binary font',
  '.eot': 'binary font',
  '.zip': 'binary archive',
  '.gz': 'binary archive',
  '.tgz': 'binary archive',
  '.br': 'binary archive',
  '.pdf': 'binary document',
  '.node': 'compiled native addon',
  '.wasm': 'compiled WebAssembly module',
  '.log': 'runtime log - relay-server.log records raw bytes off the CDP wire and is not source',
  '.tsbuildinfo': 'generated by tsc',
}

export type ScanRoot = {
  /** Path relative to the package root. '.' means the package root itself. */
  dir: string
  recursive: boolean
}

/**
 * What "tracked source file" means for this check.
 *
 * The scan walks the filesystem rather than asking `git ls-files`, on purpose:
 *
 *   - A brand-new file that has not been staged yet is exactly when this mistake gets made
 *     (you just typed the byte, you have not committed anything). `git ls-files` cannot see
 *     that file; a filesystem walk can, and catches the problem at the earliest moment.
 *   - It works without a git checkout at all - a published tarball, a shallow export, a CI
 *     job that copies the tree.
 *
 * The roots below cover every directory in this package that holds hand-written text, plus the
 * package root itself (non-recursively) for the config and entry files that live there:
 * package.json, tsconfig.json, vitest.config.ts, vitest.setup.ts, bin.js, CHANGELOG.md.
 *
 * dist/ is out of scope: it is generated. Any bad byte in dist/ came from src/, where this
 * check will already have caught it, and dist/ additionally contains bundled third-party code
 * that this package does not author. The committed binary fixtures (test/video-golden/*.png)
 * stay in scope as *files* but are skipped by extension - a check that fails on a legitimately
 * binary PNG is a check people turn off.
 */
export const SCAN_ROOTS: readonly ScanRoot[] = [
  { dir: '.', recursive: false },
  { dir: 'src', recursive: true },
  { dir: 'scripts', recursive: true },
  { dir: 'test', recursive: true },
  { dir: 'docs', recursive: true },
]

export type ByteException = {
  /** Path relative to the package root, POSIX separators. Exact match - no globs, no patterns. */
  file: string
  /**
   * The exact byte values tolerated in this file, on top of tab and newline.
   * NUL (0x00) can never be listed here; see the assertion below.
   */
  allowedBytes: readonly number[]
  /** Why the raw byte belongs in this file. Required. */
  reason: string
}

/**
 * Files allowed to contain specific raw control bytes.
 *
 * Deliberately a list of exact filenames with exact byte values, never a pattern. A rule like
 * "*.test.ts may contain control bytes" or "files that already contain ESC are fine" would let
 * a stray NUL through in every place where it actually matters. Narrowing the exception to the
 * one byte value each file genuinely needs means an accidental NUL in one of these two files
 * still fails the check.
 *
 * Adding a file here should be uncomfortable. Write down why.
 */
export const CONTROL_BYTE_EXCEPTIONS: readonly ByteException[] = [
  {
    file: 'src/kitty-graphics.test.ts',
    allowedBytes: [0x1b],
    reason:
      'Contains a vitest toMatchInlineSnapshot() of buildKittySequence() output, which is a kitty ' +
      'graphics APC sequence and therefore literally is ESC _G ... ESC backslash. vitest writes its own ' +
      'inline snapshots and `pnpm test` runs `vitest run -u`, so replacing the raw byte with a \\x1b ' +
      'escape would be undone on the very next test run. The ESC bytes are the value under test. ' +
      'Every other escape in that file is written as \\x1b, as it should be.',
  },
  // src/relay-core.test.ts used to be here, for the ESC [2m ... ESC [22m dim codes in the
  // inline snapshots of Playwright's "Call log:" output. Those three snapshots have been
  // replaced by explicit toContain() assertions on the message and on the deterministic head
  // of the call log — they had pinned the retry tail, which is a function of machine speed —
  // and the assertions match the text inside the dim codes rather than the codes themselves.
  // No raw ESC is left in the file, so the exception is gone rather than merely unused.
]

// Structural guarantee: no exception can ever whitelist NUL, which is the byte that started
// all of this and the one that makes grep give up without saying anything.
for (const exception of CONTROL_BYTE_EXCEPTIONS) {
  if (exception.allowedBytes.includes(0x00)) {
    throw new Error(
      `CONTROL_BYTE_EXCEPTIONS entry for ${exception.file} lists NUL (0x00). ` +
        'NUL is never allowed in a source file: it makes grep treat the file as binary and return ' +
        'nothing at all, with no warning. Write the escape instead.',
    )
  }
  if (exception.allowedBytes.length === 0) {
    throw new Error(`CONTROL_BYTE_EXCEPTIONS entry for ${exception.file} lists no bytes; remove the entry instead.`)
  }
  if (!exception.reason.trim()) {
    throw new Error(`CONTROL_BYTE_EXCEPTIONS entry for ${exception.file} has an empty reason; explain why.`)
  }
}

const CONTROL_BYTE_NAMES: Readonly<Record<number, string>> = {
  0x00: 'NUL',
  0x01: 'SOH',
  0x02: 'STX',
  0x03: 'ETX',
  0x04: 'EOT',
  0x05: 'ENQ',
  0x06: 'ACK',
  0x07: 'BEL',
  0x08: 'BS',
  0x09: 'TAB',
  0x0a: 'LF',
  0x0b: 'VT',
  0x0c: 'FF',
  0x0d: 'CR',
  0x0e: 'SO',
  0x0f: 'SI',
  0x10: 'DLE',
  0x11: 'DC1',
  0x12: 'DC2',
  0x13: 'DC3',
  0x14: 'DC4',
  0x15: 'NAK',
  0x16: 'SYN',
  0x17: 'ETB',
  0x18: 'CAN',
  0x19: 'EM',
  0x1a: 'SUB',
  0x1b: 'ESC',
  0x1c: 'FS',
  0x1d: 'GS',
  0x1e: 'RS',
  0x1f: 'US',
  0x7f: 'DEL',
}

export type ViolationKind = 'control-byte' | 'invalid-utf8'

export type ByteViolation = {
  /** Package-root-relative path with POSIX separators. */
  file: string
  kind: ViolationKind
  /** Byte offset from the start of the file. */
  offset: number
  /** The offending byte value, 0-255. */
  byte: number
  /** 1-based line number, counting 0x0A. */
  line: number
  /** 1-based column, measured in bytes within the line. */
  column: number
  /** One-line description of what is wrong. */
  detail: string
}

function toHexByte(byte: number): string {
  return byte.toString(16).toUpperCase().padStart(2, '0')
}

/** Renders a byte as `0x1B (ESC)`, or just `0xC3` when it has no control-character name. */
export function describeByte(byte: number): string {
  const name = CONTROL_BYTE_NAMES[byte]
  return name ? `0x${toHexByte(byte)} (${name})` : `0x${toHexByte(byte)}`
}

function isDisallowedControlByte(byte: number): boolean {
  if (byte === 0x7f) {
    return true
  }
  return byte < 0x20 && !ALLOWED_CONTROL_BYTES.has(byte)
}

/**
 * Validates UTF-8 by hand rather than through TextDecoder, because TextDecoder's fatal mode
 * throws without telling you *where* the bad byte is, and the offset is half the point of this
 * check. Rejects overlong encodings, surrogate code points and anything above U+10FFFF.
 */
export function findInvalidUtf8(bytes: Uint8Array): { offset: number; byte: number; detail: string } | null {
  let index = 0
  while (index < bytes.length) {
    const lead = bytes[index]
    if (lead < 0x80) {
      index += 1
      continue
    }

    let continuationCount: number
    let minimumCodePoint: number
    let codePoint: number
    if (lead >= 0xc2 && lead <= 0xdf) {
      continuationCount = 1
      minimumCodePoint = 0x80
      codePoint = lead & 0x1f
    } else if (lead >= 0xe0 && lead <= 0xef) {
      continuationCount = 2
      minimumCodePoint = 0x800
      codePoint = lead & 0x0f
    } else if (lead >= 0xf0 && lead <= 0xf4) {
      continuationCount = 3
      minimumCodePoint = 0x10000
      codePoint = lead & 0x07
    } else {
      return {
        offset: index,
        byte: lead,
        detail:
          `0x${toHexByte(lead)} cannot start a UTF-8 sequence ` +
          (lead >= 0x80 && lead <= 0xbf
            ? '(it is a continuation byte with no lead byte before it)'
            : '(0xC0, 0xC1 and 0xF5-0xFF never appear in valid UTF-8)'),
      }
    }

    for (let step = 1; step <= continuationCount; step += 1) {
      const offset = index + step
      if (offset >= bytes.length) {
        return {
          offset: index,
          byte: lead,
          detail: `truncated ${continuationCount + 1}-byte UTF-8 sequence: the file ends mid-character`,
        }
      }
      const continuation = bytes[offset]
      if ((continuation & 0xc0) !== 0x80) {
        return {
          offset,
          byte: continuation,
          detail: `expected a UTF-8 continuation byte (0x80-0xBF) but found 0x${toHexByte(continuation)}`,
        }
      }
      codePoint = (codePoint << 6) | (continuation & 0x3f)
    }

    if (codePoint < minimumCodePoint) {
      return {
        offset: index,
        byte: lead,
        detail: `overlong UTF-8 encoding: U+${codePoint.toString(16).toUpperCase().padStart(4, '0')} written in ${continuationCount + 1} bytes`,
      }
    }
    if (codePoint >= 0xd800 && codePoint <= 0xdfff) {
      return {
        offset: index,
        byte: lead,
        detail: `UTF-8 encoding of surrogate code point U+${codePoint.toString(16).toUpperCase()}, which is not a valid character`,
      }
    }
    if (codePoint > 0x10ffff) {
      return {
        offset: index,
        byte: lead,
        detail: `UTF-8 encoding of U+${codePoint.toString(16).toUpperCase()}, which is above the Unicode maximum U+10FFFF`,
      }
    }

    index += continuationCount + 1
  }
  return null
}

/** Offsets of the first byte of every line, so line/column lookups stay cheap. */
function computeLineStarts(bytes: Uint8Array): number[] {
  const starts = [0]
  for (let index = 0; index < bytes.length; index += 1) {
    if (bytes[index] === 0x0a) {
      starts.push(index + 1)
    }
  }
  return starts
}

function lineIndexForOffset({ lineStarts, offset }: { lineStarts: number[]; offset: number }): number {
  let low = 0
  let high = lineStarts.length - 1
  while (low < high) {
    const middle = (low + high + 1) >> 1
    if (lineStarts[middle] <= offset) {
      low = middle
    } else {
      high = middle - 1
    }
  }
  return low
}

/**
 * Finds every disallowed control byte, plus the first UTF-8 well-formedness error.
 * Results are sorted by byte offset.
 */
export function findByteViolations({
  file,
  bytes,
  allowedExtraBytes = [],
}: {
  file: string
  bytes: Uint8Array
  allowedExtraBytes?: readonly number[]
}): ByteViolation[] {
  const allowed = new Set(allowedExtraBytes)
  const lineStarts = computeLineStarts(bytes)

  const locate = (offset: number): { line: number; column: number } => {
    const index = lineIndexForOffset({ lineStarts, offset })
    return { line: index + 1, column: offset - lineStarts[index] + 1 }
  }

  const violations: ByteViolation[] = []

  for (let offset = 0; offset < bytes.length; offset += 1) {
    const byte = bytes[offset]
    if (!isDisallowedControlByte(byte) || allowed.has(byte)) {
      continue
    }
    const { line, column } = locate(offset)
    violations.push({
      file,
      kind: 'control-byte',
      offset,
      byte,
      line,
      column,
      detail: `disallowed control byte ${describeByte(byte)}`,
    })
  }

  const utf8Error = findInvalidUtf8(bytes)
  if (utf8Error) {
    const { line, column } = locate(utf8Error.offset)
    violations.push({
      file,
      kind: 'invalid-utf8',
      offset: utf8Error.offset,
      byte: utf8Error.byte,
      line,
      column,
      detail: `invalid UTF-8: ${utf8Error.detail}`,
    })
  }

  violations.sort((left, right) => {
    return left.offset - right.offset
  })
  return violations
}

/**
 * Renders a byte window as text, escaping everything outside printable ASCII as \xNN so the
 * result is unambiguous and so caret alignment is exact even when the file is not valid UTF-8.
 */
function renderEscapedWindow({
  bytes,
  start,
  end,
  target,
}: {
  bytes: Uint8Array
  start: number
  end: number
  target: number
}): { text: string; caretStart: number; caretLength: number } {
  let text = ''
  let caretStart = 0
  let caretLength = 1
  for (let offset = start; offset < end; offset += 1) {
    const byte = bytes[offset]
    const chunk = byte >= 0x20 && byte <= 0x7e ? String.fromCharCode(byte) : `\\x${toHexByte(byte)}`
    if (offset === target) {
      caretStart = text.length
      caretLength = chunk.length
    }
    text += chunk
  }
  return { text, caretStart, caretLength }
}

const LINE_WINDOW_RADIUS = 48

function renderLineContext({ bytes, violation }: { bytes: Uint8Array; violation: ByteViolation }): string {
  const lineStarts = computeLineStarts(bytes)
  const index = lineIndexForOffset({ lineStarts, offset: violation.offset })
  const lineStart = lineStarts[index]
  const lineEnd = index + 1 < lineStarts.length ? lineStarts[index + 1] - 1 : bytes.length

  const windowStart = Math.max(lineStart, violation.offset - LINE_WINDOW_RADIUS)
  const windowEnd = Math.min(lineEnd, violation.offset + LINE_WINDOW_RADIUS)
  const clippedLeft = windowStart > lineStart
  const clippedRight = windowEnd < lineEnd

  const rendered = renderEscapedWindow({ bytes, start: windowStart, end: windowEnd, target: violation.offset })
  const leftMarker = clippedLeft ? '...' : ''
  const rightMarker = clippedRight ? '...' : ''
  const body = `${leftMarker}${rendered.text}${rightMarker}`
  const caretColumn = leftMarker.length + rendered.caretStart
  const caret = `${' '.repeat(caretColumn)}${'^'.repeat(rendered.caretLength)}`

  return [
    `  line ${violation.line}, rendered with every non-printable byte escaped as \\xNN:`,
    `    ${body}`,
    `    ${caret} here`,
  ].join('\n')
}

const HEX_DUMP_RADIUS = 24

function renderHexDump({ bytes, violation }: { bytes: Uint8Array; violation: ByteViolation }): string {
  const dumpStart = Math.max(0, Math.floor((violation.offset - HEX_DUMP_RADIUS) / 16) * 16)
  const dumpEnd = Math.min(bytes.length, Math.ceil((violation.offset + HEX_DUMP_RADIUS) / 16) * 16)

  const lines: string[] = [`  raw bytes around offset ${violation.offset}:`]
  for (let rowStart = dumpStart; rowStart < dumpEnd; rowStart += 16) {
    let hexPart = ''
    let asciiPart = ''
    for (let column = 0; column < 16; column += 1) {
      const offset = rowStart + column
      if (column === 8) {
        hexPart += ' '
      }
      if (offset < bytes.length) {
        hexPart += `${toHexByte(bytes[offset])} `
        const byte = bytes[offset]
        asciiPart += byte >= 0x20 && byte <= 0x7e ? String.fromCharCode(byte) : '.'
      } else {
        hexPart += '   '
        asciiPart += ' '
      }
    }
    const prefix = `    ${rowStart.toString(16).toUpperCase().padStart(8, '0')}  `
    lines.push(`${prefix}${hexPart} |${asciiPart}|`)

    if (violation.offset >= rowStart && violation.offset < rowStart + 16) {
      const column = violation.offset - rowStart
      const markerColumn = prefix.length + column * 3 + (column >= 8 ? 1 : 0)
      lines.push(`${' '.repeat(markerColumn)}^^`)
    }
  }
  return lines.join('\n')
}

function renderWhyItMatters(violation: ByteViolation): string {
  if (violation.kind === 'invalid-utf8') {
    return [
      '  Why this matters: the file is not valid UTF-8, so anything that decodes it as text -',
      '  grep, ripgrep, editors, code review diffs, the TypeScript compiler host - will either',
      '  refuse the file or silently substitute replacement characters. Re-save the file as UTF-8.',
    ].join('\n')
  }

  if (violation.byte === 0x00) {
    return [
      '  Why this matters: a raw NUL makes GNU grep classify the whole file as binary. It then',
      '  exits 1 and prints nothing at all - no match, no warning, not even "binary file matches".',
      '  `file` reports the source as `data`. tsc and vitest are entirely unaffected, so the build',
      '  stays green while every search over the file silently returns nothing. This has already',
      '  cost one afternoon and one nearly-filed false bug report.',
      '',
      '  Fix: write the escape - `\\x00` or `\\u0000` in a string or template literal - instead of',
      '  embedding the byte. A NUL separator is a fine idea; the raw byte in the source is not.',
    ].join('\n')
  }

  if (violation.byte === 0x0d) {
    return [
      '  Why this matters: this package is LF-only. A carriage return here is either a CRLF line',
      '  ending that slipped in from another platform or a lone stray CR, and both are invisible in',
      '  an editor while showing up as noise in every diff.',
      '',
      '  Fix: convert the file to LF endings, or write `\\r` if the character is genuinely part of',
      '  the data.',
    ].join('\n')
  }

  if (violation.byte === 0x1b) {
    return [
      '  Why this matters: a raw ESC byte usually means an ANSI or terminal escape sequence was',
      '  pasted in from real terminal output. It renders as nothing in an editor, so the code reads',
      '  as if the sequence is not there at all.',
      '',
      '  Fix: write `\\x1b` instead. If the raw byte is genuinely required - for example because',
      '  vitest regenerates the literal under `vitest run -u` and would overwrite the escape - add a',
      '  named entry to CONTROL_BYTE_EXCEPTIONS in src/source-bytes.ts explaining why.',
    ].join('\n')
  }

  return [
    '  Why this matters: control bytes are invisible in an editor and change how text tooling',
    '  treats the file. Only tab (0x09) and newline (0x0A) are permitted.',
    '',
    `  Fix: write the escape - \`\\x${toHexByte(violation.byte)}\` - instead of embedding the byte. If the raw byte`,
    '  is genuinely required, add a named entry to CONTROL_BYTE_EXCEPTIONS in src/source-bytes.ts',
    '  explaining why.',
  ].join('\n')
}

/**
 * The failure message. Names the file, the byte offset, the offending byte in hex, and shows
 * the surrounding bytes twice: once as escaped text with a caret under the offender, and once
 * as a hex dump. The whole point is that the next person diagnoses this in seconds rather than
 * getting silence from grep and drawing the wrong conclusion.
 */
export function formatViolation({ violation, bytes }: { violation: ByteViolation; bytes: Uint8Array }): string {
  const headline = `${violation.file}:${violation.line}:${violation.column} - ${violation.detail}`
  const facts = [
    `  offending byte: ${describeByte(violation.byte)}`,
    `  byte offset:    ${violation.offset} (line ${violation.line}, column ${violation.column})`,
    '  allowed control bytes: 0x09 (TAB) and 0x0A (LF) only',
  ].join('\n')

  return [
    headline,
    '',
    facts,
    '',
    renderLineContext({ bytes, violation }),
    '',
    renderHexDump({ bytes, violation }),
    '',
    renderWhyItMatters(violation),
  ].join('\n')
}

/** Lists every file the check will read, as package-root-relative POSIX paths, sorted. */
export function listScannedFiles({ packageRoot = PACKAGE_ROOT }: { packageRoot?: string } = {}): string[] {
  const found: string[] = []

  const visit = ({
    absoluteDir,
    relativeDir,
    recursive,
  }: {
    absoluteDir: string
    relativeDir: string
    recursive: boolean
  }): void => {
    let entries: fs.Dirent[]
    try {
      entries = fs.readdirSync(absoluteDir, { withFileTypes: true })
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code
      if (code === 'ENOENT') {
        return
      }
      throw error
    }

    for (const entry of entries) {
      // Symlinks are skipped: following them can walk out of the package or loop forever, and
      // the real file is scanned at its real location anyway.
      if (entry.isSymbolicLink()) {
        continue
      }
      const childRelative = relativeDir ? `${relativeDir}/${entry.name}` : entry.name
      if (entry.isDirectory()) {
        if (!recursive || entry.name in SKIPPED_DIRECTORIES) {
          continue
        }
        visit({ absoluteDir: path.join(absoluteDir, entry.name), relativeDir: childRelative, recursive })
        continue
      }
      if (!entry.isFile()) {
        continue
      }
      if (path.extname(entry.name).toLowerCase() in SKIPPED_EXTENSIONS) {
        continue
      }
      found.push(childRelative)
    }
  }

  for (const root of SCAN_ROOTS) {
    visit({
      absoluteDir: path.resolve(packageRoot, root.dir),
      relativeDir: root.dir === '.' ? '' : root.dir,
      recursive: root.recursive,
    })
  }

  return [...new Set(found)].sort()
}

export type ScanResult = {
  /** Every file that was read. */
  files: string[]
  /** Every violation found, in file then offset order. */
  violations: ByteViolation[]
  /** Fully formatted failure messages, at most MAX_REPORTED_PER_FILE per file. */
  reports: string[]
  /** Exception entries whose file does not exist - a rename or a typo. Always fatal. */
  missingExceptionFiles: string[]
  /** Exception entries whose file no longer contains the allowed byte. Reported, not fatal. */
  unusedExceptions: string[]
}

const MAX_REPORTED_PER_FILE = 3

/**
 * Scans the package. Pass `applyExceptions: false` to see what the tree looks like with the
 * exception list switched off, which is how the test proves the exception list is exactly the
 * set of files that actually need one.
 */
export function scanSourceBytes({
  packageRoot = PACKAGE_ROOT,
  applyExceptions = true,
}: { packageRoot?: string; applyExceptions?: boolean } = {}): ScanResult {
  const files = listScannedFiles({ packageRoot })
  const exceptionsByFile = new Map(
    CONTROL_BYTE_EXCEPTIONS.map((exception) => {
      return [exception.file, exception] as const
    }),
  )
  const usedExceptions = new Set<string>()

  const violations: ByteViolation[] = []
  const reports: string[] = []

  for (const file of files) {
    const bytes = fs.readFileSync(path.resolve(packageRoot, file))
    const exception = exceptionsByFile.get(file)

    if (exception) {
      const withoutException = findByteViolations({ file, bytes })
      const covered = withoutException.some((candidate) => {
        return candidate.kind === 'control-byte' && exception.allowedBytes.includes(candidate.byte)
      })
      if (covered) {
        usedExceptions.add(file)
      }
    }

    const allowedExtraBytes = applyExceptions && exception ? exception.allowedBytes : []
    const fileViolations = findByteViolations({ file, bytes, allowedExtraBytes })
    if (fileViolations.length === 0) {
      continue
    }

    violations.push(...fileViolations)
    for (const violation of fileViolations.slice(0, MAX_REPORTED_PER_FILE)) {
      reports.push(formatViolation({ violation, bytes }))
    }
    if (fileViolations.length > MAX_REPORTED_PER_FILE) {
      reports.push(
        `  ... and ${fileViolations.length - MAX_REPORTED_PER_FILE} more violation(s) in ${file}; ` +
          'the offsets above are the first ones.',
      )
    }
  }

  const missingExceptionFiles: string[] = []
  const unusedExceptions: string[] = []
  for (const exception of CONTROL_BYTE_EXCEPTIONS) {
    if (!fs.existsSync(path.resolve(packageRoot, exception.file))) {
      missingExceptionFiles.push(exception.file)
      continue
    }
    if (!usedExceptions.has(exception.file)) {
      unusedExceptions.push(exception.file)
    }
  }

  return { files, violations, reports, missingExceptionFiles, unusedExceptions }
}

/**
 * CLI entry point, used by `pnpm check:source-bytes` and as the first step of `pnpm build`.
 * Returns the process exit code rather than calling process.exit, so it stays testable.
 */
export function runSourceBytesCheck({ packageRoot = PACKAGE_ROOT }: { packageRoot?: string } = {}): number {
  const result = scanSourceBytes({ packageRoot })

  for (const file of result.unusedExceptions) {
    const exception = CONTROL_BYTE_EXCEPTIONS.find((candidate) => {
      return candidate.file === file
    })
    console.warn(
      `source-bytes: warning - the exception for ${file} is no longer needed; the file contains none of ` +
        `${(exception?.allowedBytes ?? []).map(describeByte).join(', ')} any more. Delete the entry from ` +
        'CONTROL_BYTE_EXCEPTIONS in src/source-bytes.ts.',
    )
  }

  if (result.missingExceptionFiles.length > 0) {
    for (const file of result.missingExceptionFiles) {
      console.error(
        `source-bytes: CONTROL_BYTE_EXCEPTIONS names ${file}, which does not exist. ` +
          'Was it renamed or deleted? Update or remove the entry in src/source-bytes.ts.',
      )
    }
    return 1
  }

  if (result.reports.length > 0) {
    console.error('')
    console.error(
      `source-bytes: ${result.violations.length} disallowed byte(s) found in ${new Set(result.violations.map((violation) => violation.file)).size} file(s).`,
    )
    console.error('')
    for (const report of result.reports) {
      console.error(report)
      console.error('')
    }
    return 1
  }

  console.log(
    `source-bytes: ${result.files.length} files checked - all valid UTF-8, no control bytes besides tab and newline.`,
  )
  return 0
}
